apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tdkyhplg6-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/tdkyhplg6-java-quarkus-gitops